<h1 style="margin-bottom: 25px;font-size:3.5rem;color:#4c76ce;text-align:center;">
    Introduction to NumPy</h1>
    
<h2 style="margin-bottom: 25px;font-size:2.5rem;text-align:center;">
    Part III: Introduction to Linear Algebra with Numpy</h2>
    
<img src="https://raw.githubusercontent.com/lajmcourses/Images/master/numpy.png"
     style="position:absolute;top:5px;left:25px;height:150px;width:auto;margin-bottom:25px;">

# 1. Vectors

## 1.1 Vector Norm

Vector norm is a measure of vector distance.

In [27]:
import numpy as np
from numpy.linalg import norm

v1 = np.array([1, 0, -1, 3, 2])
print("\nVector v1:", v1)

# L2 Norm
norm_l2 = norm(v1, 2)
print("\nNorm L2 of v1:", norm_l2)

# L1 Norm (or Manhattan Distance)
norm_l1 = norm(v1, 1)
print("\nNorm L1 of v1:", norm_l1)

# L-inf Norm
norm_linf = norm(v1, np.inf)
print("\nNorm L-inf of v1:", norm_linf)


Vector v1: [ 1  0 -1  3  2]

Norm L2 of v1: 3.872983346207417

Norm L1 of v1: 7.0

Norm L-inf of v1: 3.0


## 1.2 Scalar Multiplication of Vectors

In [9]:
import numpy as np
from numpy.linalg import norm



[ 1  2 -3  2 -1]

Norm L2 of v1: 4.358898943540674
[ 1  0  0 -4  2]

Norm L2 of v2: 4.58257569495584

Norm L1 of v1: 9.0

Norm L1 of v2: 7.0

Norm L-inf of v1: 3.0

Norm L-inf of v2: 4.0

Vector v1: [ 1  2 -3  2 -1]

Vector v2: [ 1  0  0 -4  2]

v1 x v1 =  -9


## Exercise 0:

a) Create vector v1 = [1, -4, 10, 11, -5, 0, -2]

b) Create vector v2 = [3, 4, -12, 1, 1, 0, 15]

c) Calculate L2 norm for both of the vectors

d) Calculate the norm L1 for both of the vectors

e) Calculate the norm L-infinity for both of the vectors

f) Find the scalar product of v1 and v2

In [11]:
import numpy as np
from numpy.linalg import norm


v1 = np.array([1, -4, 10, 11, -5, 0, -2])
v2 = np.array([3, 4, -12, 1, 1, 0, 15])
print("\nVector v1:", v1)
print("\nVector v2:", v2)

norm_l2 = norm(v1, 2)
print("\nNorm L2 of v1:", norm_l2)
norm_l2 = norm(v2, 2)
print("\nNorm L2 of v2:", norm_l2)

norm_l1 = norm(v1, 1)
print("\nNorm L1 of v1:", norm_l1)

norm_l1 = norm(v2, 1)
print("\nNorm L1 of v2:", norm_l1)

norm_linf = norm(v1, np.inf)
print("\nNorm L-inf of v1:", norm_linf)

norm_linf = norm(v2, np.inf)
print("\nNorm L-inf of v2:", norm_linf)

res = np.dot(v1, v2)
print("\nv1 x v1 = ", res)











Vector v1: [ 1 -4 10 11 -5  0 -2]

Vector v2: [  3   4 -12   1   1   0  15]

Norm L2 of v1: 16.34013463836819

Norm L2 of v2: 19.8997487421324

Norm L1 of v1: 33.0

Norm L1 of v2: 36.0

Norm L-inf of v1: 11.0

Norm L-inf of v2: 15.0

v1 x v1 =  -157


# 2. Matrices

## 2.1 Matrix Norm

In [29]:
import numpy as np
from numpy.linalg import norm

m1 = np.array([
    [1, 2, 3, 4, 5],
    [1, 0, 0, -1, 3],
    [-2, 4, 5, 0, 0]
])

print("\nMatrix m1:\n", m1, "\n")


# L2 Norm
norm_l2 = norm(m1, 2)
print("\nNorm L2 of m1:", norm_l2)

# L1 Norm 
norm_l1 = norm(m1, 1)
print("\nNorm L1 of m1:", norm_l1)

# L-inf Norm
norm_linf = norm(m1, np.inf)
print("\nNorm L-inf of m1:", norm_linf)


Matrix m1:
 [[ 1  2  3  4  5]
 [ 1  0  0 -1  3]
 [-2  4  5  0  0]] 


Norm L2 of m1: 8.526655284108742

Norm L1 of m1: 8.0

Norm L-inf of m1: 15.0


## 2.2 Multiplication of Matrices

In [30]:
import numpy as np 

# Create matrices
m1 = np.array([
    [1, 7], 
    [2, 3], 
    [5, 0]
])

m2 = np.array([
    [2, 6, 3, 1], 
    [1, 2, 3, 4]
])

print("\nMatrix m1:\n", m1)
print("\nMatrix m2:\n", m2)

# Multiplying matrices
m3 = np.dot(m1, m2)
print("\nm3 = m1 x m2:\n", m3)


Matrix m1:
 [[1 7]
 [2 3]
 [5 0]]

Matrix m2:
 [[2 6 3 1]
 [1 2 3 4]]

m3 = m1 x m2:
 [[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


## 2.3 Determinant of a Matrix

In [31]:
import numpy as np
from numpy.linalg import det

# Create matrix
m = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, 0, 3],
    [0, 3, 2, 1]
])

print("\nMatrix m:\n", m)

dm = det(m)

print("\nDeterminant of m:", round(dm, 4))



Matrix m:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]

Determinant of m: -38.0


## Exercise 1:


a) Create matrix M = [[0, 2, 1, 3], [3, 2, 8, 1], [1, 0, 0, 3], [0, 3, 2, 1]].

b) Find norms L2 and L1 of the matrix

c) Find the determinant of M.

d) Create 4 x 4 identity matrix I

e) Multiplay M by I and show that the result is M


# Solution

In [4]:
import numpy as np
from numpy.linalg import det
from numpy.linalg import norm

# Create matrix
M = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, 0, 3],
    [0, 3, 2, 1]
])

print("\nMatrix M:\n", M)

#Find norms L2 and L1 of the matrix

# L2 Norm
norm_l2 = norm(M, 2)
print("\nNorm L2 of M:", norm_l2)

# L1 Norm 
norm_l1 = norm(M, 1)
print("\nNorm L1 of M:", norm_l1)

#c) Find the determinant of M
dm = det(M)
print("\nDeterminant of M:", round(dm, 4))

#Create 4 x 4 identity matrix I
I = np.identity(4)
print("Identity Matrix:\n", I, "\n")

#Multiplay M by I and show that the result is M
MI = np.dot(M, I)
print("\nMI = M x I:\n", MI)










Matrix M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]

Norm L2 of M: 9.511345872776696

Norm L1 of M: 11.0

Determinant of M: -38.0
Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 


MI = M x I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]


## 2.5 Rank of a Matrix

A rank of an *m x n* matrix *M* is the number of linearly independent columns or rows of A,
and it is denoted as *rank(A)*.

A matrix has full rank if *rank(A) = min(m, n)*.

## 2.4 Inverse Matrix

The inverse of a square matrix M is a matrix of the same size, N, such that, M x N = I.
The inverse of a matrix is analogous to an inverse number: 3 x 1/3 = 1.

A matrix is said to be invertible if it has an inverse.

The inverse of a matrix is unique, that is for an invertible matrix, there is only one inverse for that matrix.

If M is a square matrix, its inverse is denoted as $M^{-1}$

In [13]:
import numpy as np
from numpy.linalg import inv, matrix_rank

# Create matrix
m = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, -3, 3],
    [0, 1, 1, 1]
])

print("\nMatrix m:\n", m)

# Check if matrix determinant is not zero
print("\nDeterminant of m:\n", round(det(m), 4))

# Or check if the rank of the matrix is 4
mrank = matrix_rank(m)
print("\nThe rank of A:\n", mrank)

# Matrix m inverse
m_inv = inv(m)
print("\nThe inverse of m:\n", m_inv)

mI = np.dot(m,m_inv )
print("\nm3 = m x mI:\n", mI)


Matrix m:
 [[ 0  2  1  3]
 [ 3  2  8  1]
 [ 1  0 -3  3]
 [ 0  1  1  1]]

Determinant of m:
 -5.0

The rank of A:
 4

The inverse of m:
 [[-3.   0.   1.   6. ]
 [-5.  -0.4  1.2 11.8]
 [ 2.   0.2 -0.6 -4.4]
 [ 3.   0.2 -0.6 -6.4]]

m3 = m x mI:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -3.33066907e-16 -1.77635684e-15]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


## Exercise 2:

a) Create matrix mp = [[0, 1, 0], [0, 0, 0], [1, 0, 1]]

b) Show that mp has a determinant equal to 0, and hence this matrix has no inverse.

# Solution

In [11]:
import numpy as np
from numpy.linalg import det

# Create matrix
mp = np.array([
    [0, 1, 0],
    [0, 0, 0],
    [1, 0, 1]
])

print("\nMatrix mp:\n", mp)

# Show that mp has a determinant equal to 0, and hence this matrix has no inverse.
dm = det(mp)
print("\nDeterminant of mp:\n", round(det(mp), 3))



Matrix mp:
 [[0 1 0]
 [0 0 0]
 [1 0 1]]

Determinant of mp:
 0.0


## Exercise 3:

# Solution

a) Create matrix A = [[1, 0, 1], [-4, 3, 0], [1, 0, -2]]

b) Compute the rank of the matrix A

c) Find the determinant of A

d) Find the inverse of A

e) Multiply A by the inverse of A, and explain the result

In [12]:
import numpy as np
from numpy.linalg import inv, matrix_rank

# Create matrix
A = np.array([
    [1, 0, 1],
    [-4, 3, 0],
    [1, 0, -2]
])

print("\nMatrix mp:\n", A)

#b) Compute the rank of the matrix A

arank = matrix_rank(A)
print("\nThe rank of A:\n", arank)

#c) Find the determinant of A
dm = det(A)
print("\nDeterminant of A:", round(dm, 3))
print(f'matrix has a determinant unequal to 0, and hence this matrix has an inverse matrix.') 

#d) Find the inverse of A
a = inv(A)
print("\nThe inverse of A:\n", a)

# Multiply A by the inverse of A, and explain the result

Aa = np.dot(A,a)
print("\nAa = a x A:\n", Aa)






Matrix mp:
 [[ 1  0  1]
 [-4  3  0]
 [ 1  0 -2]]

The rank of A:
 3

Determinant of A: -9.0
matrix has a determinant unequal to 0, and hence this matrix has an inverse matrix.

The inverse of A:
 [[ 0.66666667 -0.          0.33333333]
 [ 0.88888889  0.33333333  0.44444444]
 [ 0.33333333 -0.         -0.33333333]]

Aa = a x A:
 [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 0.00000000e+00 1.00000000e+00]]


## 3. Solving Linear Equations Systems

A linear equation is an equality of the form

$$ \sum_{i=1}^{n} a_i x_i = y $$


A system of linear equations is a set of linear equations that share the same variables, for example:

$$ a_{11} x_1 + a_{12} x_2 + a_{13} x_3 = y_1 $$
$$ a_{21} x_1 + a_{22} x_2 + a_{23} x_3 = y_2 $$
$$ a_{31} x_1 + a_{32} x_2 + a_{33} x_3 = y_3 $$

The system of linear equations can be writtend in the matrix form:

$$ A x = y $$

where

$ A = 
\begin{bmatrix}
    a_{11} & a_{12} & a_{13} \\
    a_{21} & a_{22} & a_{23} \\
    a_{31} & a_{32} & a_{33} \\
\end{bmatrix}
$

$ x = [x_1, x_2, x_3] $

$ y = [y_1, y_2, y_3] $

## Exercise 4

Put the equations system below into matrix form:

$$ 
 4x + 3y - 5z = 2   \\
-2x - 4y + 5z = 5  \\
 7x + 8y      = -3 \\
 x +  2z      = 1 \\
 9x + y - 6z   = 6 
$$


In [31]:
# Create matrix
m = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [7, 8, 0],
    [1, 0, 2],
    [9, 1, -6]
])

'X = [x, y, z]'

y = np.array([2, 5, -3, 1,  6])


In [26]:
my = np.array([
    [4, 3, -5, 2],
    [-2, -4, 5, 5],
    [7, 8, 0, -3],
    [1, 0, 2, 1],
    [9, 1, -6, 6]
])

## 3.1 Solutions to Systems of Linear Equations

Consider a system of linear equations in matrix form, *Ax = y*, where *A* is an *m × n* matrix. 
Recall that this means there are *m* equations and *n* unknowns in our system. 
A solution to this system of linear equations is a vector *x* of size *n*. There are three possibilities:

1) The linear system has no solutions for *x*.

2) There is one unique solution *x* that solves the system of linear equations.

3) There are infinitely many solutions for *x* solving the linear equations system.


**Case 1: There is no solutions for x**

If *rank([A, y]) = rank(A) + 1* then y is linearly independent from the columns of A. 
Therefore, because *y* is not in the range of *A*, by definition there cannot
be an *x* that satisfies the equation. Thus, comparing *rank([A, y])* and *rank(A)* provides an easy
way to check if there are no solutions to a system of linear equations.


**Case 2: There is unique solution for x**

If *rank([A, y]) = rank(A)*, then y can be written as a linear combination of the columns of *A*, 
and there is at least one solution for the matrix equation. For there to be only one solution, 
*rank(A) = n* must also be true. In other words, the number of equations must be exactly equal to the number of unknowns.


**Case 3: There are infinitely many solutions for x**

If *rank([A, y]) = rank(A)*, then *y* is in the range of *A*, and there is at least one solution for the matrix equation; however, if *rank(A) < n*, then there are infinitely many solutions. 


Consider a system of linear equations in matrix form, *Ax = y*, where *A* is an *m × n* matrix. 
Recall that this means there are *m* equations and *n* unknowns in our system. 
A solution to this system of linear equations is a vector *x* of size *n*. There are three possibilities:

1) The linear system has no solutions for *x*.

2) There is one unique solution *x* that solves the system of linear equations.

3) There are infinitely many solutions for *x* solving the linear equations system.


**Case 1: There is no solutions for x**

If *rank([A, y]) = rank(A) + 1* then y is linearly independent from the columns of A. 
Therefore, because *y* is not in the range of *A*, by definition there cannot
be an *x* that satisfies the equation. Thus, comparing *rank([A, y])* and *rank(A)* provides an easy
way to check if there are no solutions to a system of linear equations.


**Case 2: There is unique solution for x**

If *rank([A, y]) = rank(A)*, then y can be written as a linear combination of the columns of *A*, 
and there is at least one solution for the matrix equation. For there to be only one solution, 
*rank(A) = n* must also be true. In other words, the number of equations must be exactly equal to the number of unknowns.


**Case 3: There are infinitely many solutions for x**

If *rank([A, y]) = rank(A)*, then *y* is in the range of *A*, and there is at least one solution for the matrix equation; however, if *rank(A) < n*, then there are infinitely many solutions. 


Consider a system of linear equations in matrix form, *Ax = y*, where *A* is an *m × n* matrix. 
Recall that this means there are *m* equations and *n* unknowns in our system. 
A solution to this system of linear equations is a vector *x* of size *n*. There are three possibilities:

1) The linear system has no solutions for *x*.

2) There is one unique solution *x* that solves the system of linear equations.

3) There are infinitely many solutions for *x* solving the linear equations system.


**Case 1: There is no solutions for x**

If *rank([A, y]) = rank(A) + 1* then y is linearly independent from the columns of A. 
Therefore, because *y* is not in the range of *A*, by definition there cannot
be an *x* that satisfies the equation. Thus, comparing *rank([A, y])* and *rank(A)* provides an easy
way to check if there are no solutions to a system of linear equations.


**Case 2: There is unique solution for x**

If *rank([A, y]) = rank(A)*, then y can be written as a linear combination of the columns of *A*, 
and there is at least one solution for the matrix equation. For there to be only one solution, 
*rank(A) = n* must also be true. In other words, the number of equations must be exactly equal to the number of unknowns.


**Case 3: There are infinitely many solutions for x**

If *rank([A, y]) = rank(A)*, then *y* is in the range of *A*, and there is at least one solution for the matrix equation; however, if *rank(A) < n*, then there are infinitely many solutions. 


## Exercise 5

How many solutions does the system have:
    
a) 
$$ 
 4x + 3y - 5z = 2   \\
-2x - 4y + 5z = 5  \\
 7x + 8y      = -3 \\
  x +  2z      = 1 \\
 9x + y - 6z   = 6
$$

b) 
$$
 2x_2 + x_3 + 3x_4 = 1 \\
 3x_1 + 2x_2 + 8x_3 + x_4 = -7 \\
 x_1 + 3x_4 = 0 \\
 4x_2 + 2x_3 + 6x_4 = 15
$$

c) 

$$
 3x_1 - x_2 + 4x_3 = 2 \\
 17x_1 + 2x_2 + x_3 = 14 \\
 x_1 + 12x_2 - 7x_3 = 54
$$


# Solution a

In [13]:
import numpy as np
from numpy.linalg import inv, matrix_rank


#a) Create matrix
A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [7, 8, 0],
    [1, 0, 2],
    [9, 1, -6]
    
])
print("\nMatrix A:\n", A)

y = np.array([2, 5, -3, 1,  6])
print("\nVector y:", y)

Ay = np.array([
    [4, 3, -5, 2],
    [-2, -4, 5, 5],
    [7, 8, 0, -3],
    [1, 0, 2, 1],
    [9, 1, -6, 6]
])
#Compute the rank of the matrix A
arank = matrix_rank(A)
print("\nThe rank of A:\n", arank)

#Compute the rank of the matrix Ay
ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:\n", ayrank)
print("\nConclusion: the rank([A, y]) = rank(A) + 1, hence there are no solutions for x.\n")




Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 7  8  0]
 [ 1  0  2]
 [ 9  1 -6]]

Vector y: [ 2  5 -3  1  6]

The rank of A:
 3

The rank of Ay:
 4

Conclusion: the rank([A, y]) = rank(A) + 1, hence there are no solutions for x.



# Solution b

In [15]:
import numpy as np
from numpy.linalg import inv, matrix_rank

# Create matrix
B = np.array([
    [0, 2, 1, 3],
    [3, 2, 8, 1],
    [1, 0, 0, 3],
    [0, 4, 2, 6],
    
])

print("\nMatrix B:\n", B)
y = np.array([1, -7, 0, 15])
print("\nVector y:", y)

By = np.array([
    [0, 2, 1, 3, 1],
    [3, 2, 8, 1,-7],
    [1, 0, 0, 3, 0],
    [0, 4, 2, 6, 15],
    
])
print("\nMatrix by:\n", By)

#Compute the rank of the matrix B
brank = matrix_rank(B)
print("\nThe rank of B:\n", brank)

#Compute the rank of the matrix by
byrank = matrix_rank(By)
print("\nThe rank of By:\n", byrank)
print("\nConclusion: the rank([B, y]) = rank(B) + 1, hence there are no solutions for x.")


Matrix B:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 4 2 6]]

Vector y: [ 1 -7  0 15]

Matrix by:
 [[ 0  2  1  3  1]
 [ 3  2  8  1 -7]
 [ 1  0  0  3  0]
 [ 0  4  2  6 15]]

The rank of B:
 3

The rank of By:
 4

Conclusion: the rank([B, y]) = rank(B) + 1, hence there are no solutions for x.


# Solution c

In [16]:
import numpy as np
from numpy.linalg import inv, matrix_rank

#b) Create matrix
C = np.array([
    [3, -1, 4],
    [17, 2, 1],
    [1, 12, -7],
])

print("\nMatrix C:\n", C)
y = np.array([2, 14, 54])
print("\nVector y:", y)

Cc = np.array([
    [3, -1, 4, 2],
    [17, 2, 1, 14],
    [1, 12, -7, 54],
    
])
#Compute the rank of the matrix B
crank = matrix_rank(C)
print("\nThe rank of C:\n", crank)

#Compute the rank of the matrix cc
ccrank = matrix_rank(Cc)
print("\nThe rank of Cc:\n", ccrank)

print("Conclusion: the rank([C, y]) = rank(C) = n, hence the system has a unique solution\n")


Matrix C:
 [[ 3 -1  4]
 [17  2  1]
 [ 1 12 -7]]

Vector y: [ 2 14 54]

The rank of C:
 3

The rank of Cc:
 3
Conclusion: the rank([C, y]) = rank(C) = n, hence the system has a unique solution



## 3.2 Solving Linear Equations Systems with Numpy

Let's solve the linear system from the exercise 5:

$$ 
 4x + 3y - 5z = 2   \\
-x - 2y + 3z = 3  \\
 8x + 2y - 2z = 3 \\
$$

The number of unknowns *n=3*. The number of equations *m=5*.

The first step is to write down the equation in the matrix form.

The next step is to determine if the equation has a solution. It means that we need to find the ranks of the matrices *A* and *[A,y]*.

Finally, if the solution exist we need to find it.

In [35]:
# Solution

import numpy as np
from numpy.linalg import solve, matrix_rank

# Matrix A

A = np.array([
    [4, 3, -5],
    [-1, -2, 3],
    [8, 2, -2], 
])
print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 3, 3])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.array([
    [4, 3, -5, 2],
    [-1, -2, 3, 3],
    [8, 2, -2, 3]
])

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution\n")

# Solving the linear equations system
x = solve(A, y)

print("\nSolution to the system: x:", x)

# Testing the solution
Ax = np.dot(A, x)
print("\nAx:", Ax)


Matrix A:
 [[ 4  3 -5]
 [-1 -2  3]
 [ 8  2 -2]]

Rank of A: 3

Vector y: [2 3 3]

Matrix [A,y]:
 [[ 4  3 -5  2]
 [-1 -2  3  3]
 [ 8  2 -2  3]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence there are no solutions for x.


Solution to the system: x: [ 1.58333333 -9.91666667 -5.08333333]

Ax: [2. 3. 3.]


## Exercise 6

a) Show that the system has a unique solution:
    
$$
4x_1 + 3x_2 - 5x_3 = 2 \\
-2x_1 - 4x_2 + 5x_3 = 5 \\
8x_1 + 8x_2 = -3
$$

b) Solve the linear equations system

### a) Show that the system has a unique solution:


In [7]:
import numpy as np
from numpy.linalg import solve, matrix_rank

A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [8, 8, 0], 
])
print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 5, -3])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.array([
    [4, 3, -5, 2],
    [-2,-4 ,5, 5],
    [8, 8, 0, -3]
])

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution\n")


Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]

Rank of A: 3

Vector y: [ 2  5 -3]

Matrix [A,y]:
 [[ 4  3 -5  2]
 [-2 -4  5  5]
 [ 8  8  0 -3]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution



### b) Solve the linear equations system

In [61]:
import numpy as np
from numpy.linalg import solve, matrix_rank

A = np.array([
    [4, 3, -5],
    [-2, -4, 5],
    [8, 8, 0], 
])
print("\nMatrix A:\n", A)

y = np.array([2, 5, -3])
print("\nVector y:", y)

x = solve(A, y)

print("\nSolution to the system: x:", x)

Ax = np.dot(A, x)
print("\nAx:", Ax)


Matrix A:
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]

Vector y: [ 2  5 -3]

Solution to the system: x: [ 2.20833333 -2.58333333 -0.18333333]

Ax: [ 2.  5. -3.]


## Exercise 7

a) Show that the system has a unique solution:

$$
    3x_1 - x_2 + 4x_3 = 2 \\
    17x_1 + 2x_2 + x_3 = 14 \\
    x_1 + 12x_2 + 7x_3 = 54 \\
$$

b) Solve the linear equations system

In [8]:
import numpy as np
from numpy.linalg import solve, matrix_rank

#a) Show that the system has a unique solution:
A = np.array([
    [3, -1, 4],
    [17, 2, 1],
    [1, 12, 7],])

print("\nMatrix A:\n", A)

arank = matrix_rank(A)
print("\nRank of A:", arank)

y = np.array([2, 14, 54])
print("\nVector y:", y)

# Matrix [A, y]
Ay = np.array([
    [3, -1, 4, 2],
    [17, 2, 1, 14],
    [1, 12, 7, 54],])

print("\nMatrix [A,y]:\n", Ay)

ayrank = matrix_rank(Ay)
print("\nThe rank of Ay:", ayrank)

print("\nConclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution\n")

#b) Solve the linear equations system


x = solve(A, y)

print("\nSolution to the system: x:", x)

Ax = np.dot(A, x)
print("\nAx:", Ax)




Matrix A:
 [[ 3 -1  4]
 [17  2  1]
 [ 1 12  7]]

Rank of A: 3

Vector y: [ 2 14 54]

Matrix [A,y]:
 [[ 3 -1  4  2]
 [17  2  1 14]
 [ 1 12  7 54]]

The rank of Ay: 3

Conclusion: the rank(A) = rank(Ay) = n, hence the system has a unique solution


Solution to the system: x: [0.30901288 3.76824034 1.21030043]

Ax: [ 2. 14. 54.]
